name: run lib test

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [1.0.0, 0.42.0]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: deno setup
      uses: denolib/setup-deno@master
      with:
        deno-version: ${{ matrix.deno }}
    - name: run test
      run:
        deno test
